# Generated by Django 3.2.13 on 2024-08-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=50)),
                ('class_number', models.CharField(max_length=10)),
                ('student_pd', models.CharField(max_length=50)),
                ('parent_pd', models.CharField(max_length=50)),
            ],
        ),
    ]
